apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - http-route.yaml
  - svc.yaml
  - configmap.yaml
  - projects
  # Applications are not included here as they depend on ArgoCD being deployed first
  # Use 'make argocd-apply-apps' to apply them separately

# Configure ArgoCD to be accessible through the Gateway API
patches:
  - target:
      kind: Service
      name: argocd-server
    patch: |-
      - op: replace
        path: /spec/type
        value: ClusterIP