apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-ravilspace
  namespace: gateway
spec:
  dnsNames:
    - "*.ravil.space"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cloudflare-cluster-issuer
  secretName: cert-ravilspace
  usages:
    - digital signature
    - key encipherment