---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: config-cloudflare-ddns
  namespace: ddns
spec:
  encryptedData:
    config.json: AgBRvqSObZliKPl72GV1umbfvUvdydczpEguAvS/EW3WJMwYXi9yW3lXVJhZcJIn6yrnChbUG5YYajYTIp1ngSN2xczv7DIxooksPfDAoc5TIK8Yj0iFfEvLKN0O0PHZqMhDYqiXe34XYVgFYrJAXHcxjniT4uVYYYrtHDcU4GImB5uXTf8UIpOphVxEte+azLsXes5nBmDbmCssJUVHIMS0vb5QaNSiTYFQ0UjuIEEliphVFK2qP7XZOyzew2R+iNe8ntB2rOb2fxZsG0GgnP72DQaArMVcLWRa005X7mrm4QHuS1WJ6pQkzxiQAmfAaT/vPhTyma75lDcLeYcxiZs7Jo+McbZNl419E+AHNtaUXv69pUYK1rPdgpPf8fxwqLrlZ3VCICpyANWE+TBtRuQdv26r8ARU4hWfoG892stKz8mO5vlJtPX1Aqe1xKvclS6xIOJhFJvEbaQ+ZLby2WCIV+6eyGrmDuMm6yLAwj5YCfCMl0gi23xGuaTMzVG7I1U+inTSpJDNBBipsUKUo+EVF552Yi4D7RCMfvcWsRXMdDhZk1t3wJoHhQt1xhIfcf/Z1W8JgIrwJHnesqgzx570CC+656dFBeNRx2JhADH4J14AlsKb6xi7fQGNT4AKELyL012p3AttZVZNa3PTKdsjnTi5kp4TloND4TbTpvE0b0Zgeb7VoapEvZj6oZMSpyzfJpeDnwkiOsXm298Ia7S94hAkKRu0GRSNtYBWE0jt+uaTvcO5svqbyvJd64eqeG2j+KzE3HwTazQQ1hS51SsjZ0J1DCXveKEmFChhFmCXK8vp+9bmrWAwYkp4d2yKVTQRaikggC4qAfNoKPk8Gbsz2LTXwaL6Z73dPcHkzh7YoXX5uxAJ1IMKKUvNncwbm1BQ8XfLojj7x1OJkExiHoakdZRPx61S+xgP8v0QL9XH5u/+h83kIu2xCSIH91G6hG50QQGCzTjLtRaCSQdEc2ivYfH2QSTXf4vsQHVRdAfMK/ly4VW/8HbOxuP9wpkdDq9WoqMcKtBKg3DXWDK8AnfwVFs593frDvvH209qarLqgiGD2XMPwSv+3afesnDWL7osf3DsMHrBfch2lkbaXc2MSkAZXoVjcislZ4TFf4q6nPPdSpBytUH+kfkRIFhDO0/RSKJImVAgAgAWKjZe9lLY8nTAHplULFBum1bcQw==
  template:
    metadata:
      creationTimestamp: null
      name: config-cloudflare-ddns
      namespace: ddns
