---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: config-cloudflare-ddns
  namespace: ddns
spec:
  encryptedData:
    config.json: AgCWxoO7PWwiZY24wQA3zFw523feMSK5E0eyQszzfbWm33rKD5JAH1+Il5BMTKxWvbxTJsQOwYEnjPRLSCXHxNMYLAT8V0wz7k66AX112goyVVgCPW2VDNwswT4hSEsjAZbO46Npk41UovbO1MUIrJuGGgSdxLe+HQVRETWksV8JIWlZLA/tJauK+kkvLcVrFWLX1ls7zzF3EDbDYnsBiIuT/BxPae3HBkX/Ttw6ttQp2KCGEzXBMw5EDHK7+EHGJAVL8D5+J/to0x7aooEL4SwAFNjmKKTRd4h6SEqGNpiLVSLYI95cTNSRNM0LMXmygGaWpbjmwDvIEmyWFqou94Ot0n61xSyS2d/35SCKxSJ7STxIgMpNUVQpSGgn/4dl0Wtj8sm3HrgQJBAN5zyF68QVD9qAMaAuIqP0GVPqcaVenR3rvVXDvb9Wm4bANLa7AOElGO3rd/rZedSmVcDOjwYkb3etWAd4flRbVFHl/qoaWFRleGZD2dL95zcc/7lr+iWjXXdt+3/XMpD1d+5xlMJJ/tPqbOsg2/htVcrZOLaRmpVQnqXzG9A1vV13dfekIZ5Xc4rqO0qvzmIBozxKPCPJAiUQOCVcyKsFhUjc/HmfU1CdkIbHwy0a8euAlXY8HPoHS0FuV0ZccUqaHQQdaCywXxr4FAU4L1u3qiycRayCE05cKwoqfBUeIwhZRVPdBaRhqZ6eHxuUj5Wz/hgydc6j5LmJ4jgZhUCUKy3yDC7ZD1vzV422lI3jXTl63fIIaaWJqw2gpzAq5ka1pjYNrTUDrPyd/t14l3LvKRLXodvIUIMjJhc9pQQvsBwEcbdpDnpLp/N5hNUKZQxbOADHdV1zPzABOYmmKecQihxCE7pDLyuAr3KB5XAwbXnk42zor8Q6COHyfL84NOBWidPuxPFT1XmVrobRkCP/4q1ANA5PjnstBgNJEiLAggPgmbEzu46smHI46Gb3Py8f8NgWi1nI5ix5KwYtdzfd0SH6axTnQZgXTz5iCKlbt8hJAE7E8qonZo9lXUfqVPriErQrrQT7apWewoKj97Pv/plE3aG39yeJc9HUWwHVK7ZsMuS8O6GyG6k2u5PH2Em39n7e8FDkrFO4q4rz+XCYpMXNEOTuKtqHm9asOLEgrB1H8lFEz1KqBXuSRShCFJS12TWSSsxi7lwWZZ4mzVxAtAqhLA==
  template:
    metadata:
      creationTimestamp: null
      name: config-cloudflare-ddns
      namespace: ddns
