---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: config-cloudflare-ddns
  namespace: ddns
spec:
  encryptedData:
    config.json: AgCxa3827puA/tzNEdKxa6AIWIXG8L/3+CIQAv8h5ZBysaSkn2ez41mi3f2YMLU7QwzNWP9STmByFV9rPkOp9HucdRQQPpKc87a5YYqMDXvcuZOvHKoZd0CP4P77pvc4Xt9t7vca6wtoH/1/GXvtMZ3g2gCVs8qzLNsJxIvFOWFJG8iEgl4xzyEgxdEDdDH4CXT91tBB7PmkeNxOwycb2Vp9c0gkUuvYc2G/DfdLCExFxb+PsDwzG4C9x2p0F4iKkdaT2fOd/6yw2Z+fXPfxRz8dYdZE/lTm56Pvpk7A6n5BxpWhpV5X/bzRRj+u9oPgABfSpH6l5QiMi81f9o7nXXERkoodG22vtgnqKUlIEU1nWj380VEqR6BxfnhQbzW4kLOe2KhPQsfvfCUUzgt3rf8FRZ3L7A08ghU7/ZbyQqanvmJEi3IX0PpfQi3i/xzC8HHGCQ47+0lullN5C6YZEbXf37FmJ1uOECO9tbr+DI8usClfghl1c2Pjucz6hJyYYe36o7bXnDQpyhrJYMKBFqIYBqoNc9xzpZl04eN/EzUC7HCSz0EplO95vU1Ayn2hqdJtrSOoDDKDvKgJchW7falamPCXiKAMtMCcDnVLArUSCgOEkcaesFqzl7snnNrCsSCt7+E1m2N33FQuAAjm7XC1MXvKYmIp+sYKR189HQuZ1DyNyzHOhhKaNwUqj4Rl5zRq/fe6vU1PzuHl/OV7ur4nabTMNE18nN3YQ47/nV9Z/wnpIaEVOFwhGYtiDlqyRfjca+sAlzo9JIPRhXEOgwmVnLo7tu7uyg/5R1iHuTWb50EFN/YZX0yInroaaZsaGk/dPq0JgDkz3P6NtFeMn+SiZqyqRc0kX5py/lX+yEzZCCPKbJGnAUNpkQeCvQJTeDg+VQvRuTNQWRfFUQAjN6d1MPfBWwf3zWCRRznKBkJjk9MK7nvtkcfOUwZUSuYh7HUHa5fYssUNPdIgQErmdhucg1jr+K60FuK55cL0yZSKNR8daUeStvqJkvww2CUIJWgGB9aW+W7crlm+BcnfEi4SzD/NvlO0cCJ2WsQDRIS3KSaIg44iVw90Wp+G7XxunxkrkrXuK52THtU9w6c4En1n8b1OhpJH4mr6zgY9Y72VoKm0k8CqKmCQ0XPegZu5ZMMNv4ky/h1bGukWabQAHDSgnOODIENMDWkQq1b5Og==
  template:
    metadata:
      creationTimestamp: null
      name: config-cloudflare-ddns
      namespace: ddns
