apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: homelab
  namespace: argocd
spec:
  description: Homelab infrastructure and applications
  
  # Allow applications to be created from any git repository
  sourceRepos:
  - '*'
  
  # Only deploy to specific namespaces
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  
  # Allow creating resources of any kind
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'