apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/ravilushqa/homelab.git
        revision: HEAD
        directories:
          - path: k8s/apps/external/*
          - exclude: true
            path: k8s/apps/external/README.md
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: homelab
      source:
        repoURL: https://github.com/ravilushqa/homelab.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true 