apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-services
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/ravilushqa/homelab.git
    targetRevision: HEAD
    path: k8s/apps/external
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 