apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/ravilushqa/homelab.git
    targetRevision: HEAD
    path: k8s/infra
    directory:
      recurse: true
      exclude: argocd/**
      jsonnet: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true 