apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glance
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/ravilushqa/homelab.git
    targetRevision: HEAD
    path: k8s/apps/internal/glance
  destination:
    server: https://kubernetes.default.svc
    namespace: glance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: isponsorblocktv
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/ravilushqa/homelab.git
    targetRevision: HEAD
    path: k8s/apps/internal/isponsorblocktv
  destination:
    server: https://kubernetes.default.svc
    namespace: isponsorblocktv
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 