apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: homelab
  namespace: argocd
spec:
  description: Homelab project containing all internal and external applications
  
  # Allow manifests to deploy from any Git repository
  sourceRepos:
    - '*'
  
  # Allow deploying to any namespace
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  
  # Allow all resource kinds
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*' 