apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - gateway-route.yaml
  - applications/

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 5.53.2
    releaseName: argocd
    namespace: argocd
    includeCRDs: true
    valuesInline:
      server:
        ingress:
          enabled: false  # Disabled since we're using Gateway API
        extraArgs:
          - --insecure # Required since TLS termination happens at the Gateway
      configs:
        cm:
          url: https://argocd.ravil.space
          # Additional settings for better UX
          statusbadge.enabled: 'true'
          kustomize.buildOptions: --enable-helm
          resource.customizations.health.argoproj.io_Application: |
            hs = {}
            hs.status = "Progressing"
            hs.message = ""
            if obj.status ~= nil then
              if obj.status.health ~= nil then
                hs.status = obj.status.health.status
                if obj.status.health.message ~= nil then
                  hs.message = obj.status.health.message
                end
              end
            end
            return hs
        rbac:
          policy.default: role:readonly
          policy.csv: |
            p, role:org-admin, applications, *, */*, allow
            p, role:org-admin, clusters, get, *, allow
            p, role:org-admin, repositories, *, *, allow
            p, role:org-admin, projects, *, *, allow
            g, admin, role:org-admin