apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - gateway-route.yaml

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 5.53.2
    releaseName: argocd
    namespace: argocd
    includeCRDs: true
    valuesInline:
      server:
        ingress:
          enabled: false  # Disabled since we're using Gateway API
        extraArgs:
          - --insecure # Required since TLS termination happens at the Gateway
      configs:
        cm:
          url: https://argocd.ravil.space
        rbac:
          policy.default: role:readonly
          policy.csv: |
            p, role:org-admin, applications, *, */*, allow
            p, role:org-admin, clusters, get, *, allow
            p, role:org-admin, repositories, *, *, allow
            p, role:org-admin, projects, *, *, allow
            g, admin, role:org-admin 