resources:
  - deployment.yaml
  - svc.yaml
  - configmap.yaml
  - http-route.yaml
  - ns.yaml
configMapGenerator:
  - name: config-glance
    namespace: glance
    behavior: replace
    files:
      - glance.yml