apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hoarder
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ravilushqa/homelab
    targetRevision: HEAD
    path: k8s/apps/internal/hoarder
  destination:
    server: https://kubernetes.default.svc
    namespace: hoarder
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true