apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: isponsorblocktv
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ravilushqa/homelab
    targetRevision: HEAD
    path: k8s/apps/internal/isponsorblocktv
  destination:
    server: https://kubernetes.default.svc
    namespace: isponsorblocktv
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
