apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: home-assistant
  namespace: haos
spec:
  parentRefs:
    - name: external
      namespace: gateway
  hostnames:
    - "haos.kube.ravil.space"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: home-assistant
          namespace: haos
          port: 8123
