apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace resource
resources:
  - namespace.yaml

# Use our component
components:
  - ../../../components/tls-service

# Service-specific patches
patches:
  # Update Service
  - patch: |-
      - op: replace
        path: /metadata/name
        value: proxmox
      - op: replace
        path: /metadata/namespace
        value: proxmox
      - op: replace
        path: /spec/ports/0/targetPort
        value: 8006
    target:
      kind: Service
      name: service-name

  # Update EndpointSlice
  - patch: |-
      - op: replace
        path: /metadata/name
        value: proxmox
      - op: replace
        path: /metadata/namespace
        value: proxmox
      - op: replace
        path: /metadata/labels/kubernetes.io~1service-name
        value: proxmox
      - op: replace
        path: /ports/0/port
        value: 8006
      - op: replace
        path: /endpoints/0/addresses/0
        value: 192.168.1.100
    target:
      kind: EndpointSlice
      name: service-name

  # Update TLSRoute
  - patch: |-
      - op: replace
        path: /metadata/name
        value: proxmox-tls
      - op: replace
        path: /metadata/namespace
        value: proxmox
      - op: replace
        path: /spec/hostnames/0
        value: proxmox.ravil.space
      - op: replace
        path: /spec/rules/0/backendRefs/0/name
        value: proxmox
      - op: replace
        path: /spec/rules/0/backendRefs/0/port
        value: 443
    target:
      kind: TLSRoute
      name: service-name-tls