apiVersion: v1
kind: Pod
metadata:
  name: net-utils
  namespace: default
spec:
  containers:
  - name: net-utils
    image: nicolaka/netshoot
    command: ["/bin/bash", "-c", "while true; do sleep 30; done;"]
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
