apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dozzle
resources:
  - namespace.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - oauth2-proxy-config.yaml
  - oauth2-proxy-deployment.yaml
  - oauth2-proxy-service.yaml
  - sealed-config.yaml