apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-config
  namespace: dozzle
data:
  oauth2-proxy.cfg: |
    # OAuth2 Provider Configuration
    provider = "oidc"
    provider_display_name = "PocketID"
    oidc_issuer_url = "https://pocketid.ravil.space"
    
    # Client Configuration
    client_id = "$(OAUTH2_PROXY_CLIENT_ID)"
    client_secret = "$(OAUTH2_PROXY_CLIENT_SECRET)"
    
    # Cookie Configuration
    cookie_name = "_oauth2_proxy_dozzle"
    cookie_secret = "$(OAUTH2_PROXY_COOKIE_SECRET)"
    cookie_secure = true
    cookie_httponly = true
    cookie_samesite = "lax"
    cookie_domains = ".ravil.space"
    
    # Server Configuration
    http_address = "0.0.0.0:4180"
    reverse_proxy = true
    real_client_ip_header = "X-Forwarded-For"
    
    # Upstream Configuration
    upstreams = ["http://dozzle:8080"]
    
    # Session Configuration
    session_store_type = "cookie"
    
    # Email Configuration
    email_domains = ["*"]
    
    # Security Configuration
    pass_basic_auth = false
    pass_access_token = false
    pass_user_headers = true
    set_xauthrequest = true
    
    # Logging
    silence_ping_logging = true