apiVersion: v1
kind: ServiceAccount
metadata:
  name: dozzle-service-account
  namespace: dozzle
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dozzle-cluster-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dozzle-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: dozzle-service-account
  namespace: dozzle
roleRef:
  kind: ClusterRole
  name: dozzle-cluster-role
  apiGroup: rbac.authorization.k8s.io